spring.application.name=demo

# H2 데이터베이스 웹 콘솔 활성화
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# DB 접속 정보 설정
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA가 자동으로 DB 테이블을 만들어주도록 설정
spring.jpa.hibernate.ddl-auto=update
# 실행되는 SQL 쿼리를 콘솔창에 보여주기
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
